### ISSUE TITLE
[Mutagen] Folders created in container are synced to host as 0700 despite configuration

### ISSUE THREAD

**Issue by kierenevans** [inviqa/harness-base-php#238]
Files are also synced to host as 0600.

Configuration:
```
forward:
  project:
    source: "tcp:localhost:6060"
    destination: "docker://project-sync:tcp:localhost:6060"

sync:
  project:
    alpha: "."
    beta: "docker://project-sync/app"
    mode: "two-way-resolved"
    configurationBeta:
      permissions:
        defaultOwner: "id:999"
        defaultGroup: "id:999"
        defaultFileMode: 0644
        defaultDirectoryMode: 0755
    symlink:
      mode: posix-raw
    ignore:
      paths:
        - /.docker-sync
        - /.idea
        - /.git
        - /var
```

Steps to reproduce:
```
■ > docker-compose exec -u build console bash
build@8d4f74504f9c:/app$ touch test
build@8d4f74504f9c:/app$ ls -la test
-rw-r--r-- 1 build build 0 Mar 12 06:06 test
build@8d4f74504f9c:/app$ exit
```
Then on host:
```
ls -la test
-rw-------  1 kevans  staff  0 12 Mar 08:06 test
```
