### ISSUE TITLE
Use a file based opcache for CLI tasks in production mode

### ISSUE THREAD

**Issue by kierenevans** [inviqa/harness-base-php#495]
CLI processes do not have a shared memory area to share between runs, so each time PHP compiles a file to run the CLI task, the bytecode of the compiled PHP scripts are thrown away.

Configuring a file based cache can help with this, though it can be a bit tricky to manage.

We have found success configuring the following to speed up behat scenarios based on the symfony behat extension:
```yaml
attribute('php.cli.ini'):
  opcache.file_cache: "= (@('app.build') == 'static' ? '/tmp/php-file-cache' : '')"
  opcache.file_cache_only: "= (@('app.build') == 'static' ? '1' : '0')"
  opcache.file_cache_consistency_checks: "= (@('app.build') == 'static' ? '1' : '0')"
```
and making sure the build user can edit that directory in Dockerfile steps: `chown -R build:build /tmp/php-file-cache/`

This could be extended from the console container to any cron or runner containers.
