### ISSUE TITLE
Some subset of /app/public/media should be a shared volume on Akeneo

### ISSUE THREAD

**Issue by andytson-inviqa** [inviqa/harness-base-php#607]
On a project we need at least /app/public/media/cache to be a shared RWX volume so that nginx can serve cache of file resizes of uploaded images.

We're not sure if /media/ itself should be shared though

**Comment by a-ast** [comment]
Uploaded images and other files are stored in `var/file_storage/` and those folder can be configured in 
`config/packages/{ENV}/oneup_flysystem.yml`:

```yaml
oneup_flysystem:
    adapters:
        asset_storage_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/asset'
        catalog_storage_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/catalog'
        jobs_storage_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/jobs'
        archivist_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/archive'
        data_quality_insights_shared_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/data_quality_insights_shared'
```
