### ISSUE TITLE
Add support for docker compose cli

### ISSUE THREAD

**Issue by andytson-inviqa** [inviqa/harness-base-php#614]
docker compose cli will be replacing docker-compose at some point. Docker Desktop already includes it under `docker compose` and has a plan to migrate docker-compose over to it, starting with an experimental feature that makes `docker-compose` call `docker compose`

Trying it out I found some initial issues with `ws external-images config` but there may be more issues

**Comment by kierenevans** [comment]
From `docker compose config`:
```yaml
# ...
  relay:
    build:
      context: /Users/kevans/Sites/example/.my127ws/docker/image/relay
      dockerfile: /Users/kevans/Sites/example/.my127ws/docker/image/relay/Dockerfile
```
```
docker compose version
Docker Compose version v2.0.0-rc.2
```

This bubbles up to errors with `ws external-images pull`

Raised https://github.com/docker/compose-cli/issues/2063 for the difference, but might be intentional
